mode = "performance"

[[default.curve]]
temp = 0
speed = 0

[[default.curve]]
temp = 46
speed = 20

[[default.curve]]
temp = 51
speed = 37

[[default.curve]]
temp = 56
speed = 45

[[default.curve]]
temp = 71
speed = 50

[[default.curve]]
temp = 76
speed = 70

[[default.curve]]
temp = 81
speed = 80

[[default.curve]]
temp = 86
speed = 90

[[default.curve]]
temp = 94
speed = 100

[[performance.curve]]
temp = 0
speed = 30

[[performance.curve]]
temp = 46
speed = 40

[[performance.curve]]
temp = 51
speed = 55

[[performance.curve]]
temp = 56
speed = 70

[[performance.curve]]
temp = 66
speed = 85

[[performance.curve]]
temp = 76
speed = 100

[[cool.curve]]
temp = 42
speed = 0

[[cool.curve]]
temp = 46
speed = 20

[[cool.curve]]
temp = 51
speed = 35

[[cool.curve]]
temp = 56
speed = 45

[[cool.curve]]
temp = 66
speed = 60

[[cool.curve]]
temp = 76
speed = 75

[[cool.curve]]
temp = 86
speed = 90
