name: Release

on:
  push:
    tags:
      - 'v[0-9]+.*'
  workflow_dispatch:   # <-- Add this line to enable manual runs

permissions:
  contents: write

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build release binary
        run: cargo build --release

      - name: Prepare release folder
        run: |
          mkdir -p release/omen-fan
          cp target/release/omen-fan release/omen-fan/
          cp install.sh release/omen-fan/
          cp src/omen-fan.service release/omen-fan/
          cp src/fan_config.toml release/omen-fan/

      - name: Create GitHub Release
        uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Upload Linux Binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: omen-fan
          target: x86_64-unknown-linux-gnu
          archive: omen-fan-x86_64-unknown-linux-gnu
          tar: unix
          token: ${{ secrets.GITHUB_TOKEN }}
          include: |
            release/omen-fan/omen-fan
            release/omen-fan/install.sh
            release/omen-fan/omen-fan.service
            release/omen-fan/fan_config.toml
